[tool.poetry]
name = "baker"
version = "1.0.0.0"
description = "An \"sh\" alternative"
authors = ["shadowrylander <titaniumfiles@outlook.com>"]
license = "GPL-3.0"
include = [
	"baker/**/*.py",
]

[tool.poetry.dependencies]
python = "^3.8"
addict = "*"
pout = {version = "*", optional = true}
sarge = "*"
toml = "*"
nanite = {git = "https://gitlab.com/picotech/nanotech/nanite.git", branch = "master"}
gensing = {git = "https://gitlab.com/picotech/nanotech/gensing.git", branch = "master"}
autoslot = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.extras]
p = ["pout"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
