[tool.poetry]
name = "bakery"
version = "1.0.0.0"
description = "An \"sh\" alternative"
authors = ["shadowrylander <titaniumfiles@outlook.com>"]
license = "OREO"
include = [
	"bakery/**/*.py",
	"bakery/**/*.hy",
]

[tool.poetry.dependencies]
python = "^3.9"
addict = "*"
autoslot = "*"
fabric = "*"
hy = "^1.0a4+4.gaa2e878"
hyrule = "*"
toolz = "*"
pout = "*"
rich = {git = "https://github.com/shadowrylander/rich.git", branch = "master"}
toml = "*"
nanite = {git = "https://gitlab.com/picotech/nanotech/nanite.git", branch = "master"}
gensing = {git = "https://gitlab.com/picotech/nanotech/gensing.git", branch = "master"}

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
