[tool.poetry]
name = "baker"
version = "1.0.0.0"
description = "An \"sh\" alternative"
authors = ["shadowrylander <titaniumfiles@outlook.com>"]
license = "GPL-3.0"
include = [
	"baker/**/*.py",
]

[tool.poetry.dependencies]
python = "^3.8"
addict = "*"
autoslot = "*"
fabric = "*"
pout = "*"
toml = "*"
nanite = {git = "https://gitlab.com/picotech/nanotech/nanite.git", branch = "master", optional = true}
gensing = {git = "https://gitlab.com/picotech/nanotech/gensing.git", branch = "master", optional = true}

[tool.poetry.extras]
full = ["nanite", "gensing"]

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
