
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='baker',
    version='1.0.0.0',
    description='An "sh" alternative',
    python_requires='==3.*,>=3.8.0',
    author='shadowrylander',
    author_email='titaniumfiles@outlook.com',
    license='GPL-3.0',
    packages=['baker'],
    package_dir={"": "."},
    package_data={},
    install_requires=['addict', 'autoslot', 'fabric', 'gensing', 'nanite', 'pout', 'toml'],
    dependency_links=['git+https://gitlab.com/picotech/nanotech/gensing.git@master#egg=gensing', 'git+https://gitlab.com/picotech/nanotech/nanite.git@master#egg=nanite'],
    extras_require={"dev": ["pytest==3.*,>=3.0.0"]},
)
