(import bakery [ls])
(import oreo)
(import oreo [nots?])
(import pathlib [Path])
(require hyrule [->])
(setv cookies (/ (.resolve (. (Path __file__) parent parent) :strict True) "cookies"))
(setv cookies-ls (.ls oreo cookies))
(setv assorted-cookies (.ls oreo cookies :sort True))
(defn not-zero? [i] (and (.isnumeric i) (not (in "0" i))))
(setv ones (sorted (gfor i cookies-ls :if (not-zero? i) i)))
(setv not-ones (sorted (gfor i cookies-ls :if (not (not-zero? i)) i)))
(defn test-filtered-output-function [] (-> cookies (ls :m/list True :m/sort None :m/filter not-zero?) (= ones) (assert)))
(defn test-filtered-output-collection [] (-> cookies (ls :m/list True :m/sort None :m/filter #(True not-zero?)) (= not-ones) (assert)))
