(import bakery [ls])
(import oreo)
(import oreo [nots?])
(import pathlib [Path])
(require hyrule [->])
(setv cookies (/ (.resolve (. (Path __file__) parent parent) :strict True) "cookies"))
(setv cookies-ls (.ls oreo cookies))
(setv assorted-cookies (.ls oreo cookies :sort True))
(defn test-list-output-short [] (-> cookies (ls :m/list True) (isinstance list) (assert)))
(defn test-list-output-long [] (-> cookies (ls :m/type list) (isinstance list) (assert)))
