(import bakery [ls])
(import oreo)
(import oreo [nots?])
(import pathlib [Path])
(import pytest [mark])
(require hyrule [->])
(setv cookies (/ (.resolve (. (Path __file__) parent parent) :strict True) "cookies"))
(setv cookies-ls (.ls oreo cookies))
(setv assorted-cookies (.ls oreo cookies :sort True))
(defn [mark.error] test-ignore-error [] (assert (ls :j True :m/ignore-stderr True)))
(defn [mark.error] test-stdout-error [] (assert (= (ls :j True :m/stdout-stderr True :m/str True)
                                                   "ls: invalid option -- 'j'\nTry 'ls --help' for more information.")))
(defn [mark.error] test-false-error [] (assert (= (ls :j True :m/false-stderr True) False)))
(defn [mark.error] test-replace-error []
      (assert (ls :j True :m/replace-stderr True))
      (-> (ls :j True :m/replace-stderr "replace error test") (= "replace error test") assert))
