(import bakery [ls])
(import oreo)
(import oreo [nots?])
(import pathlib [Path])
(import pytest [mark])
(require hyrule [->])
(setv cookies (/ (.resolve (. (Path __file__) parent parent) :strict True) "cookies"))
(setv cookies-ls (.ls oreo cookies))
(setv assorted-cookies (.ls oreo cookies :sort True))
(import os [chdir])
(require oreo [with-cwd])
(defn [mark.loop] test-loop [] (with-cwd cookies (for [item ls] (assert (in item cookies-ls)))))
