(import bakery [ls])
(import oreo)
(import oreo [nots?])
(import pathlib [Path])
(import pytest [mark])
(require hyrule [->])
(setv cookies (/ (.resolve (. (Path __file__) parent parent) :strict True) "cookies"))
(setv cookies-ls (.ls oreo cookies))
(setv assorted-cookies (.ls oreo cookies :sort True))
(import bakery [cat])
(setv bulbasaur (sorted #("001: Bulbasaur" "002: Ivysaur" "003: Venusaur" ))
      last-three (sorted #("058: Growlithe" "059: Arcanine" "060: Poliwag" ))
      one-cookie (/ cookies "01"))
(defn [mark.trim] test-trim []
      (try (.bake- cat :m/list True :m/sort None)
           (-> one-cookie (cat :m/n-lines 3) (= bulbasaur) assert)
           (-> one-cookie (cat :m/n-lines #(3)) (= bulbasaur) assert)
           (-> one-cookie (cat :m/n-lines { "number" 3 }) (= bulbasaur) assert)
           (-> one-cookie (cat :m/n-lines #(True 3)) (= last-three) assert)
           (-> one-cookie (cat :m/n-lines { "last" True "number" 3 }) (= last-three) assert)
           (finally (.splat- cat))))
